<?xml version="1.0"?>
<package format="3">
  <name>rqt_marine_radar</name>
  <version>0.0.0</version>
  <description>The rqt_marine_radar package</description>

  <maintainer email="roland@ccom.unh.edu">Roland Arsenault</maintainer>

  <license>BSD</license>
  
  <buildtool_depend>ament_cmake</buildtool_depend>
  <doc_depend>doxygen</doc_depend>
  <depend>marine_radar_control_msgs</depend>
  <depend>marine_sensor_msgs</depend>
  <depend>rclcpp</depend>
  <depend>rqt_gui</depend>
  <depend>qt_gui_cpp</depend>
  <depend>rqt_gui_cpp</depend>

  <export>
    <build_type>ament_cmake</build_type>
    <rqt_gui plugin="${prefix}/plugin.xml"/>
  </export>
</package>

